# Generated by Django 4.1.2 on 2022-10-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_number', models.CharField(max_length=20, unique=True)),
                ('eng_number', models.CharField(max_length=20)),
                ('part_name', models.CharField(max_length=200)),
                ('part_length', models.FloatField(blank=True, max_length=10)),
                ('part_material', models.CharField(blank=True, max_length=20)),
                ('image', models.FilePathField(path='/img')),
            ],
            options={
                'ordering': ['qb_number'],
            },
        ),
    ]
