# Generated by Django 4.1.2 on 2022-10-20 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_number', models.CharField(max_length=50, unique=True, verbose_name='Quick Books Number')),
                ('eng_number', models.CharField(max_length=50, verbose_name='Engineering Number')),
                ('part_name', models.CharField(max_length=200, verbose_name='Part Name')),
                ('part_length', models.FloatField(blank=True, max_length=10, verbose_name='Part Length (inches)')),
                ('part_material', models.CharField(blank=True, max_length=20, verbose_name='Part Material')),
            ],
            options={
                'ordering': ['qb_number'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=10, unique=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('quantity', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('machine_deadline', models.DateField()),
                ('product', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='jobs.product', verbose_name='Quick Books Number for Product')),
            ],
            options={
                'ordering': ['-create_date', '-start_date'],
            },
        ),
    ]
