# Generated by Django 4.1.2 on 2022-10-30 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_number', models.CharField(max_length=50, unique=True, verbose_name='Quick Books Number')),
                ('eng_number', models.CharField(max_length=50, verbose_name='Engineering Number')),
                ('part_name', models.CharField(max_length=200, verbose_name='Part Name')),
                ('part_length', models.FloatField(blank=True, max_length=10, verbose_name='Part Length (inches)')),
                ('part_material', models.CharField(blank=True, max_length=20, verbose_name='Part Material')),
                ('part_raw_mtl_cost', models.FloatField(blank=True, default=0.0, max_length=10, verbose_name='Part Cost in Raw Material')),
                ('part_vend_name', models.CharField(blank=True, max_length=500, verbose_name='Vendor Part Name')),
                ('part_vend_cost', models.CharField(blank=True, max_length=50, verbose_name='Purchase from Vendor Cost')),
                ('part_used_in', models.CharField(blank=True, max_length=500, verbose_name='Part, Where Used')),
                ('part_current_rev', models.CharField(blank=True, max_length=10, verbose_name='Current Revision')),
                ('part_image_file', models.FileField(blank=True, max_length=10, upload_to='', verbose_name='Image of the Part')),
                ('part_current_drw', models.FileField(blank=True, max_length=10, upload_to='', verbose_name='Current PDF of Part Drawing')),
                ('part_manf_op1', models.FileField(blank=True, max_length=10, upload_to='', verbose_name='1st GCode Attachment')),
                ('part_manf_op2', models.FileField(blank=True, max_length=10, upload_to='', verbose_name='2nd GCode Attachment')),
                ('part_manf_op3', models.FileField(blank=True, max_length=10, upload_to='', verbose_name='3rd GCode Attachment')),
                ('part_manf_op4', models.FileField(blank=True, max_length=10, upload_to='', verbose_name='4th GCode Attachment')),
            ],
            options={
                'ordering': ['qb_number'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=10, unique=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('quantity', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('machine_deadline', models.DateField()),
                ('product', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='jobs.product', verbose_name='Quick Books Number for Product')),
            ],
            options={
                'ordering': ['-create_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_assembly_number', models.CharField(max_length=50, unique=True, verbose_name='Quick Books Assembly Number')),
                ('assembly_number', models.CharField(max_length=10, unique=True, verbose_name='Assembly Engineering Number')),
                ('product', models.ManyToManyField(to='jobs.product', verbose_name='Quick Books Number for Part')),
            ],
            options={
                'ordering': ['qb_assembly_number'],
            },
        ),
    ]
