# Generated by Django 4.1.2 on 2022-10-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part_raw_mtl_cost',
            field=models.FloatField(blank=True, default=0.0, max_length=10, verbose_name='Part Cost in Raw Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='part_vend_cost',
            field=models.CharField(blank=True, max_length=50, verbose_name='Purchase from Vendor Cost'),
        ),
        migrations.AddField(
            model_name='product',
            name='part_vend_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Vendor Part Name'),
        ),
    ]
