# Generated by Django 4.1.2 on 2022-11-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_serial_number', models.CharField(max_length=50, unique=True, verbose_name='Asset Serial Number')),
                ('asset_owner', models.CharField(max_length=10, unique=True, verbose_name='Asset Owner')),
                ('asset_product_name', models.ManyToManyField(to='jobs.product', verbose_name='Asset Product Name')),
            ],
            options={
                'ordering': ['asset_serial_number'],
            },
        ),
    ]
