# Generated by Django 4.1.2 on 2022-10-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='QCD Job Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='eng_number',
            field=models.CharField(max_length=20, verbose_name='Engineering Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_length',
            field=models.FloatField(blank=True, max_length=10, verbose_name='Part Length (inches)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_material',
            field=models.CharField(blank=True, max_length=20, verbose_name='Part Material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_name',
            field=models.CharField(max_length=200, verbose_name='Part Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qb_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Quick Books Number'),
        ),
    ]
