# Generated by Django 4.1.2 on 2022-10-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_product_part_raw_mtl_cost_product_part_vend_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part_current_drw',
            field=models.CharField(blank=True, max_length=10, verbose_name='Current PDF of Part Drawing'),
        ),
        migrations.AddField(
            model_name='product',
            name='part_current_rev',
            field=models.CharField(blank=True, max_length=10, verbose_name='Current Revision'),
        ),
        migrations.AddField(
            model_name='product',
            name='part_manf_op1',
            field=models.CharField(blank=True, max_length=10, verbose_name='1st GCode Attachment'),
        ),
        migrations.AddField(
            model_name='product',
            name='part_manf_op2',
            field=models.CharField(blank=True, max_length=10, verbose_name='2nd GCode Attachment'),
        ),
        migrations.AddField(
            model_name='product',
            name='part_manf_op3',
            field=models.CharField(blank=True, max_length=10, verbose_name='3rd GCode Attachment'),
        ),
        migrations.AddField(
            model_name='product',
            name='part_manf_op4',
            field=models.CharField(blank=True, max_length=10, verbose_name='4th GCode Attachment'),
        ),
        migrations.AddField(
            model_name='product',
            name='part_used_in',
            field=models.CharField(blank=True, max_length=500, verbose_name='Part, Where Used'),
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_assembly_number', models.CharField(max_length=50, unique=True, verbose_name='Quick Books Assembly Number')),
                ('assembly_number', models.CharField(max_length=10, unique=True, verbose_name='Assembly Engineering Number')),
                ('product', models.ManyToManyField(to='jobs.product', verbose_name='Quick Books Number for Part')),
            ],
            options={
                'ordering': ['qb_assembly_number'],
            },
        ),
    ]
