# Generated by Django 4.1.2 on 2022-10-20 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_product_image_alter_job_job_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='product',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='jobs.product', verbose_name='Quick Books Number for Product'),
        ),
    ]
