# Generated by Django 4.1.2 on 2022-11-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_asset_asset_sale_price_product_part_sale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='product',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-job_number']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='part_used_in',
        ),
        migrations.DeleteModel(
            name='Assembly',
        ),
    ]
