# Generated by Django 4.1.2 on 2022-11-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_assembly_product_delete_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part_tool',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tool For Part'),
        ),
    ]
